services:
  marketing:
    container_name: replybase-marketing
    build: .
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - replybase_net

networks:
  replybase_net:
    external: true
