version: "3.9"

services:
  marketing:
    build:
      context: .
    container_name: replybase-marketing
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - replybase_net
    expose:
      - "3000"

networks:
  replybase_net:
    external: true
